import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { fetchRemoteModelContext } from './model';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const OUTPUT_FILE = path.join(__dirname, '..', 'data', 'model-config.json');

async function main() {
  console.log('Fetching model data...');
  const modelContext = await fetchRemoteModelContext();
  if (!modelContext) {
    console.error('Failed to fetch model context');
    process.exit(1);
  }
  const count = Object.keys(modelContext).length;

  console.log(`Found total ${count} models.`);

  const output = {
    _comment: 'Auto-generated by scripts/update-model-config.ts',
    _updated: new Date().toISOString(),
    models: modelContext
  };

  const dir = path.dirname(OUTPUT_FILE);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  fs.writeFileSync(OUTPUT_FILE, JSON.stringify(output, null, 2) + '\n', 'utf-8');
  console.log(`Updated ${OUTPUT_FILE}`);
}

main().catch((err) => {
  console.error('Failed:', (err as Error).message);
  process.exit(1);
});
